### ISSUE TITLE
Connectivity Score implementation

### ISSUE THREAD

**Issue by ceiron61** [cmap/cmapR#53]
Hi Ted,

Not really an issue per se, but I was wondering if you have any plans to extend the package to also compute the Connectivity Score as implemented by Subramanian et al., 2017?

Alternatively, are you aware of any other R package or code snippets that implement it?

Thank you,
Enrico

**Comment by tnat1031** [comment]
Hi @enricoferrero ,

Sorry for the delayed reply. We don't have immediate plans to implement the full set of connectivity scores (weighted enrichment, normalization, conversion to tau) in cmapR, particularly because the latter steps are quite involved and require access to precomputed background enrichment score distributions, which may not be generally possible. 

We do however offer the full connectivity workflow as a set of docker containers:
https://hub.docker.com/r/cmap/sig_introspect_tool/ - for computing pairwise connectivities within a dataset
https://hub.docker.com/r/cmap/sig_gutcbackground_tool/ - for converting pairwise connectives into a background for computing tau
https://hub.docker.com/r/cmap/sig_gutc_tool/ - for computing tau values

The [GSEA-MSigDB R package](https://github.com/GSEA-MSigDB/GSEA_R) implements the enrichment score (function `GSEA.EnrichmentScore`), which may be useful if that's something you'd like to compute.

Thanks a lot,
Ted
